# Generated by Django 3.2.10 on 2022-01-07 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('tagline', models.CharField(max_length=120, verbose_name='Beer style')),
                ('description', models.TextField(blank=True, default='')),
                ('og', models.FloatField(blank=True, null=True, verbose_name='Gęstość początkowa BLG')),
                ('fg', models.FloatField(blank=True, null=True, verbose_name='Gęstość końcowa BLG')),
                ('abv', models.FloatField(blank=True, null=True)),
                ('ibu', models.IntegerField(blank=True, null=True)),
                ('ebc', models.IntegerField(blank=True, null=True)),
                ('ph', models.IntegerField(blank=True, null=True)),
                ('attenuation_level', models.FloatField(blank=True, null=True)),
                ('beer_volume', models.FloatField()),
                ('unit', models.CharField(choices=[('litres', 'litres')], max_length=50)),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='created at')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='last updated')),
                ('preparation_time', models.IntegerField(verbose_name='Full time for beer project')),
            ],
        ),
        migrations.CreateModel(
            name='MashTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_temperature', models.IntegerField()),
                ('unit', models.CharField(choices=[('celsius', 'celsius')], max_length=10)),
                ('duration', models.IntegerField(help_text='How long in minutes')),
                ('sequence', models.IntegerField(choices=[(1, 'first'), (2, 'second'), (3, 'third'), (4, 'fourth'), (5, 'fifth'), (6, 'sixth'), (7, 'seventh'), (8, 'eighth'), (9, 'ninth'), (10, 'tenth')])),
                ('beer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='BeerProject.beer')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.IntegerField(choices=[(1, 'malt'), (2, 'hops'), (3, 'yeast'), (4, 'other')])),
                ('description', models.TextField(blank=True, default='')),
                ('value', models.FloatField()),
                ('unit', models.CharField(choices=[('litres', 'litres'), ('kilograms', 'kilograms'), ('grams', 'grams'), ('item', 'item')], max_length=50)),
                ('ebc', models.IntegerField(blank=True, null=True)),
                ('purpose', models.CharField(blank=True, choices=[('bittering', 'bittering'), ('aroma', 'aroma'), ('dual use', 'dual use'), ('malt', 'malt')], max_length=50, null=True)),
                ('aac', models.IntegerField(blank=True, null=True, verbose_name='Alfa acid')),
                ('country', models.CharField(blank=True, max_length=120)),
                ('sequence', models.IntegerField(choices=[(1, 'first'), (2, 'second'), (3, 'third'), (4, 'fourth'), (5, 'fifth'), (6, 'sixth'), (7, 'seventh'), (8, 'eighth'), (9, 'ninth'), (10, 'tenth')])),
                ('sequence_unit', models.CharField(default='', max_length=120, verbose_name='W której minucie dodać składnik')),
                ('beer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='BeerProject.beer')),
            ],
            options={
                'verbose_name_plural': 'Ingredients',
            },
        ),
        migrations.CreateModel(
            name='Fermentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_temperature', models.IntegerField()),
                ('unit', models.CharField(choices=[('celsius', 'celsius')], max_length=10)),
                ('duration', models.IntegerField(blank=True, help_text='How long in days', null=True)),
                ('sequence', models.IntegerField(choices=[(1, 'first'), (2, 'second'), (3, 'third'), (4, 'fourth'), (5, 'fifth')])),
                ('beer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='BeerProject.beer')),
            ],
        ),
        migrations.CreateModel(
            name='BoilVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('unit', models.CharField(choices=[('litres', 'litres')], max_length=10)),
                ('substance', models.CharField(max_length=120)),
                ('beer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='BeerProject.beer')),
            ],
        ),
        migrations.CreateModel(
            name='BeerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='product_images')),
                ('beer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='BeerProject.beer')),
            ],
        ),
    ]
