# Generated by Django 3.2.10 on 2022-01-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeerProject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boilvolume',
            name='beer',
        ),
        migrations.AddField(
            model_name='beerproject',
            name='preparation_time',
            field=models.IntegerField(default=5, verbose_name='Full time for beer project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fermentation',
            name='sequence',
            field=models.IntegerField(choices=[(1, 'first'), (2, 'second'), (3, 'third'), (4, 'fourth'), (5, 'fifth')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mashtemp',
            name='sequence',
            field=models.IntegerField(choices=[(1, 'first'), (2, 'second'), (3, 'third'), (4, 'fourth'), (5, 'fifth'), (6, 'sixth'), (7, 'seventh'), (8, 'eighth'), (9, 'ninth'), (10, 'tenth')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beer',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='country',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
