# Generated by Django 3.2.10 on 2022-01-04 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BeerProject', '0002_auto_20220104_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beer',
            old_name='beer_value',
            new_name='beer_volume',
        ),
    ]
