# Generated by Django 3.2.11 on 2022-01-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeerProject', '0003_alter_beer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='purpose',
            field=models.CharField(blank=True, choices=[('bittering', 'bittering'), ('aroma', 'aroma'), ('dual use', 'dual use')], max_length=50, null=True),
        ),
    ]
