# Generated by Django 3.2.11 on 2022-11-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeerProject', '0004_alter_ingredients_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='brew',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
