# Generated by Django 3.2.11 on 2022-11-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeerProject', '0006_alter_beer_ebc'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='concern',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
