# Generated by Django 3.2.11 on 2022-11-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeerProject', '0007_beer_concern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='concern',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='concern',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
