# Generated by Django 3.2.11 on 2022-11-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeerProject', '0008_auto_20221105_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='ebc',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
