# Generated by Django 3.2.10 on 2022-01-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeerProject', '0009_alter_beer_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boilvolume',
            name='unit',
            field=models.CharField(choices=[('litres', 'litres')], max_length=10),
        ),
    ]
