# Generated by Django 3.2.11 on 2022-11-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeerProject', '0009_alter_ingredients_ebc'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='alc',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
