# Generated by Django 3.2.10 on 2022-01-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeerProject', '0010_alter_boilvolume_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='sequence',
            field=models.IntegerField(choices=[(1, 'first'), (2, 'second'), (3, 'third'), (4, 'fourth'), (5, 'fifth'), (6, 'sixth'), (7, 'seventh'), (8, 'eighth'), (9, 'ninth'), (10, 'tenth')], default=1),
            preserve_default=False,
        ),
    ]
