# Generated by Django 3.2.11 on 2022-11-09 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BeerProject', '0013_auto_20221109_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beer',
            name='abv',
        ),
    ]
