# Generated by Django 3.2.10 on 2022-01-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeerProject', '0013_auto_20220104_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mashtemp',
            name='unit',
            field=models.CharField(choices=[('celsius', 'celsius')], max_length=10),
        ),
    ]
