# Generated by Django 3.2.10 on 2022-01-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeerProject', '0014_alter_mashtemp_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fermentation',
            name='unit',
            field=models.IntegerField(choices=[('celsius', 'celsius')]),
        ),
    ]
