# Generated by Django 3.2.11 on 2022-11-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeerProject', '0015_delete_beerimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='brew',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='beer',
            name='preparation_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Full time for beer project'),
        ),
    ]
