# Generated by Django 3.2.10 on 2022-01-04 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeerProject', '0016_alter_fermentation_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fermentation',
            name='duration',
            field=models.IntegerField(blank=True, help_text='How long in days', null=True),
        ),
        migrations.AlterField(
            model_name='fermentation',
            name='unit',
            field=models.CharField(choices=[('celsius', 'celsius')], max_length=10),
        ),
    ]
