# Generated by Django 3.2.10 on 2022-01-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeerProject', '0017_auto_20220104_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='beer_volume',
            field=models.FloatField(),
        ),
    ]
