# Generated by Django 3.2.11 on 2022-12-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeerProject', '0017_alter_boilvolume_substance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boilvolume',
            name='unit',
            field=models.CharField(choices=[('litres', 'litres')], default='litres', max_length=10),
        ),
    ]
