# Generated by Django 3.2.10 on 2022-01-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeerProject', '0018_alter_beer_beer_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='sequence_unit',
            field=models.CharField(max_length=120, verbose_name='W której minucie dodać składnik'),
        ),
    ]
