# Generated by Django 3.2.11 on 2022-12-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeerProject', '0018_alter_boilvolume_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='aac',
            field=models.FloatField(blank=True, null=True, verbose_name='Alfa acid'),
        ),
    ]
