# Generated by Django 3.2.10 on 2022-01-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeerProject', '0019_alter_ingredients_sequence_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='unit',
            field=models.CharField(choices=[('litres', 'litres'), ('kilograms', 'kilograms'), ('grams', 'grams'), ('item', 'item')], max_length=50),
        ),
    ]
