# Generated by Django 3.2.10 on 2022-01-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeerProject', '0020_alter_ingredients_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='sequence_unit',
            field=models.CharField(default='', max_length=120, verbose_name='W której minucie dodać składnik'),
        ),
    ]
