# Generated by Django 3.2.11 on 2022-12-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeerProject', '0020_beer_bootled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='brew_date',
            field=models.DateField(blank=True, null=True, verbose_name='brewed at'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='bootled_date',
            field=models.DateField(blank=True, null=True, verbose_name='bootled at'),
        ),
    ]
