# Generated by Django 3.2.11 on 2022-12-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeerProject', '0021_auto_20221227_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='sequence_unit',
            field=models.CharField(default='1', max_length=120, verbose_name='W której minucie dodać składnik'),
        ),
    ]
