# Generated by Django 3.2.10 on 2022-01-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeerProject', '0021_alter_ingredients_sequence_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beerimage',
            name='image',
            field=models.ImageField(null=True, upload_to='product_images'),
        ),
    ]
