# Generated by Django 3.2.11 on 2022-12-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeerProject', '0023_auto_20221228_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='boiling_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Full time for boiling'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='preparation_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Full time for mash up'),
        ),
    ]
