# Generated by Django 3.2.10 on 2022-01-04 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CalculatorApp', '0004_ingredients_beer'),
    ]

    operations = [
        migrations.AddField(
            model_name='beerimage',
            name='beer',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='CalculatorApp.beer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boilvolume',
            name='beer',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='CalculatorApp.beer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='method',
            name='beer',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='CalculatorApp.beer'),
            preserve_default=False,
        ),
    ]
