# Generated by Django 3.2.10 on 2022-01-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalculatorApp', '0007_auto_20220104_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='purpose',
            field=models.CharField(blank=True, choices=[('bittering', 'bittering'), ('aroma', 'aroma'), ('dual use', 'dual use'), ('malt', 'malt')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='unit',
            field=models.CharField(choices=[('litres', 'litres'), ('kilograms', 'kilograms'), ('grams', 'grams')], max_length=50),
        ),
    ]
