# Generated by Django 3.2.10 on 2022-01-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalculatorApp', '0008_auto_20220104_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='unit',
            field=models.CharField(choices=[('litres', 'litres')], max_length=50),
        ),
    ]
