# Generated by Django 3.2.10 on 2022-01-04 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CalculatorApp', '0012_ingredients_sequence_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='fermentation',
            name='beer',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='CalculatorApp.beer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mashtemp',
            name='beer',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='CalculatorApp.beer'),
            preserve_default=False,
        ),
    ]
