# Generated by Django 3.2.10 on 2022-01-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CalculatorApp', '0015_alter_fermentation_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fermentation',
            name='duration',
            field=models.CharField(blank=True, help_text='How long in days', max_length=10, null=True),
        ),
    ]
